### ISSUE TITLE
Feature request: implement make_subplots functionality

### ISSUE THREAD

**Issue by AndreiDegtiarev** [fslaborg/XPlot#76] opened 2018-08-04 10:24 UTC
In comparison to python version of plotly library, the subplots functionality I'm mostly missing in Xplot. Target behavior see https://plot.ly/python/subplots/
See also discussion [fsprojects/IfSharp#186](https://github.com/fsprojects/IfSharp/issues/186)
I believe, that this feature is the enabler for many machine learning helper algorithms that are already implemented in the python libraries (like Pandas or Seaborn) which make life of data engineers much easier.

**Comment by cartermp** [comment] 2019-11-08 18:17
Closing as duplicate of #54

**Closed as completed by cartermp** 2019-11-08 18:17 UTC
