### ISSUE TITLE
dotnetcore compatibility

### ISSUE THREAD

**Issue by cloudRoutine** [fslaborg/XPlot#37] opened 2016-07-01 03:16 UTC
are there any plans for this?

**Comment by TahaHachana** [comment] 2016-07-23 17:14
Yes, by following the related discussion on slack the picture is becoming more clear but I'll wait to see how the FsLab story is going to evolve too.

**Comment by dsyme** [comment] 2017-06-27 17:40
Duplicate of https://github.com/fslaborg/XPlot/issues/56

**Closed by dsyme** 2017-06-27 17:40 UTC
